### ISSUE TITLE
add a package for easy installation

### ISSUE THREAD

**Issue by MPBCoder** [tahadostifam/Shalgam-Hypr-DE#6]
hello, 
to make the installation and upgrading of config easier, i suggest you to also add a package for this config. also check this config for inspiration:
https://github.com/mylinuxforwork/dotfiles

**Comment by tahadostifam** [comment]
Hi. 
You know it already has a small installation script but the problem is it can't install required packages itself and user needs to install the packages separately by package managers like Pacman, Zypper, Apt, etc.

**Comment by MPBCoder** [comment]
as far i know you can make a (maybe meta) package that depends on those requirements and then clone this repo and runs the install.sh:))
as far i know it's not very hard, i can help if possible:)
